### PR TITLE
feat: add CITATION.cff file for Zenodo/Github

### PR DESCRIPTION
**Pull request by jrs65**

### CODE REVIEW

**Review by ljgray — APPROVED** [review]

**Comment by jrs65** [comment]
I do not know why the test and RTD build has suddenly started failing 😡

**Comment by ljgray** [comment]
RTD is because cython is imported all lowercase now, not sure exactly when they changed it

**Comment by ljgray** [comment]
Ignore my previous comment, that makes no sense...

**Comment by jrs65** [comment]
At last!

**Pull request merged**
